// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordSolution.CmsV2.Infrastructure.Persistence;

#nullable disable

namespace WordSolution.CmsV2.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CmsV2DbContext))]
    [Migration("20260624171728_RebuildTeachingNotes")]
    partial class RebuildTeachingNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.AtomicSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("AtomicSections", (string)null);
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.AtomicSectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AtomicSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AtomicSectionPanelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LockedContentBlockVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReferenceMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeachingRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("TitleOverride")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AtomicSectionPanelId");

                    b.HasIndex("ContentBlockId");

                    b.HasIndex("LockedContentBlockVersionId");

                    b.HasIndex("AtomicSectionId", "SortOrder");

                    b.HasIndex("AtomicSectionId", "AtomicSectionPanelId", "SortOrder");

                    b.ToTable("AtomicSectionItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_AtomicSectionItems_LockedVersionRequiresVersion", "\"ReferenceMode\" <> 2 OR \"LockedContentBlockVersionId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.AtomicSectionPanel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AtomicSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeachingRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AtomicSectionId", "SortOrder");

                    b.HasIndex("AtomicSectionId", "TeachingRole", "Difficulty")
                        .IsUnique()
                        .HasDatabaseName("UX_AtomicSectionPanels_AtomicSectionId_TeachingRole_Difficulty");

                    b.ToTable("AtomicSectionPanels", null, t =>
                        {
                            t.HasCheckConstraint("CK_AtomicSectionPanels_TeachingRole", "\"TeachingRole\" <> 0");
                        });
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.ContentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuestionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("SectionId");

                    b.ToTable("ContentBlocks", (string)null);
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.ContentBlockRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LockedContentBlockVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReferenceMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleOverride")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildBlockId");

                    b.HasIndex("LockedContentBlockVersionId");

                    b.HasIndex("ParentBlockId", "SortOrder");

                    b.ToTable("ContentBlockRelations", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContentBlockRelations_LockedVersionRequiresVersion", "\"ReferenceMode\" <> 2 OR \"LockedContentBlockVersionId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_ContentBlockRelations_NoDirectSelfReference", "\"ParentBlockId\" <> \"ChildBlockId\"");
                        });
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.ContentBlockVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocxPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlPreviewPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartParseMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PartParseStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlainText")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentBlockId", "IsCurrent");

                    b.HasIndex("ContentBlockId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ContentBlockVersions", (string)null);
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.ContentBlockVersionPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentBlockVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlainText")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceStyleNamesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentBlockVersionId", "PartType")
                        .IsUnique();

                    b.HasIndex("ContentBlockVersionId", "SortOrder");

                    b.ToTable("ContentBlockVersionParts", (string)null);
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.GeneratedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputFormId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VersionManifestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OutputFormId");

                    b.ToTable("GeneratedFiles", (string)null);
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.Handout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Handouts", (string)null);
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.HandoutVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("HandoutId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HandoutId", "SortOrder");

                    b.ToTable("HandoutVersions", (string)null);
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.HandoutVersionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandoutVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleOverride")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HandoutVersionId", "SortOrder");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("HandoutVersionItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_HandoutVersionItems_TargetType", "\"TargetType\" IN (1, 2, 4)");
                        });
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.OutputForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Audience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandoutVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutputFormat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutputTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VisibilityMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OutputTemplateId");

                    b.HasIndex("HandoutVersionId", "SortOrder");

                    b.ToTable("OutputForms", (string)null);
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.OutputTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateDocxPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OutputTemplates", (string)null);
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeachingTopicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeachingTopicId")
                        .IsUnique();

                    b.HasIndex("TeachingTopicId", "SortOrder");

                    b.ToTable("Sections", (string)null);
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.SectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LockedContentBlockVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReferenceMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectionLayer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeachingUseOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleOverride")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LockedContentBlockVersionId");

                    b.HasIndex("ParentItemId");

                    b.HasIndex("SectionId", "SortOrder");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("SectionItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_SectionItems_ContentBlockReferenceMode", "\"TargetType\" = 1 OR (\"ReferenceMode\" = 1 AND \"LockedContentBlockVersionId\" IS NULL)");

                            t.HasCheckConstraint("CK_SectionItems_LockedVersionRequiresVersion", "\"ReferenceMode\" <> 2 OR \"LockedContentBlockVersionId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_SectionItems_TargetType", "\"TargetType\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.SectionVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SectionId", "SortOrder");

                    b.ToTable("SectionVariants", (string)null);
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.SectionVariantItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SectionItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionVariantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SectionItemId");

                    b.HasIndex("SectionVariantId", "SectionItemId")
                        .IsUnique();

                    b.HasIndex("SectionVariantId", "SortOrder");

                    b.ToTable("SectionVariantItems", (string)null);
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.TagBinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetType", "TargetId");

                    b.HasIndex("TagId", "TargetType", "TargetId")
                        .IsUnique();

                    b.ToTable("TagBindings", null, t =>
                        {
                            t.HasCheckConstraint("CK_TagBindings_TargetId", "\"TargetId\" > 0");

                            t.HasCheckConstraint("CK_TagBindings_TargetType", "\"TargetType\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.TeachingNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EffectLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoteType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedTime");

                    b.ToTable("TeachingNotes", null, t =>
                        {
                            t.HasCheckConstraint("CK_TeachingNotes_EffectLevel", "\"EffectLevel\" IS NULL OR \"EffectLevel\" IN (0, 1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_TeachingNotes_NoteType", "\"NoteType\" IN (1, 2, 3, 4, 5, 6, 7)");
                        });
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.TeachingNoteBinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeachingNoteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TargetType", "TargetId");

                    b.HasIndex("TeachingNoteId", "TargetType", "TargetId")
                        .IsUnique();

                    b.ToTable("TeachingNoteBindings", null, t =>
                        {
                            t.HasCheckConstraint("CK_TeachingNoteBindings_TargetId", "\"TargetId\" > 0");

                            t.HasCheckConstraint("CK_TeachingNoteBindings_TargetType", "\"TargetType\" IN (1, 2, 3, 4, 5, 6)");
                        });
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.TeachingTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("TeachingTopics", (string)null);
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.AtomicSection", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.AtomicSectionItem", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.AtomicSection", null)
                        .WithMany()
                        .HasForeignKey("AtomicSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordSolution.CmsV2.Domain.Entities.AtomicSectionPanel", null)
                        .WithMany()
                        .HasForeignKey("AtomicSectionPanelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordSolution.CmsV2.Domain.Entities.ContentBlock", null)
                        .WithMany()
                        .HasForeignKey("ContentBlockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordSolution.CmsV2.Domain.Entities.ContentBlockVersion", null)
                        .WithMany()
                        .HasForeignKey("LockedContentBlockVersionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.AtomicSectionPanel", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.AtomicSection", null)
                        .WithMany()
                        .HasForeignKey("AtomicSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.ContentBlock", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.ContentBlockVersion", null)
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordSolution.CmsV2.Domain.Entities.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.ContentBlockRelation", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.ContentBlock", null)
                        .WithMany()
                        .HasForeignKey("ChildBlockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordSolution.CmsV2.Domain.Entities.ContentBlockVersion", null)
                        .WithMany()
                        .HasForeignKey("LockedContentBlockVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordSolution.CmsV2.Domain.Entities.ContentBlock", null)
                        .WithMany()
                        .HasForeignKey("ParentBlockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.ContentBlockVersion", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.ContentBlock", null)
                        .WithMany()
                        .HasForeignKey("ContentBlockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.ContentBlockVersionPart", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.ContentBlockVersion", null)
                        .WithMany()
                        .HasForeignKey("ContentBlockVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.GeneratedFile", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.OutputForm", null)
                        .WithMany()
                        .HasForeignKey("OutputFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.HandoutVersion", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.Handout", null)
                        .WithMany()
                        .HasForeignKey("HandoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.HandoutVersionItem", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.HandoutVersion", null)
                        .WithMany()
                        .HasForeignKey("HandoutVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.OutputForm", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.HandoutVersion", null)
                        .WithMany()
                        .HasForeignKey("HandoutVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordSolution.CmsV2.Domain.Entities.OutputTemplate", null)
                        .WithMany()
                        .HasForeignKey("OutputTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.Section", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.TeachingTopic", null)
                        .WithMany()
                        .HasForeignKey("TeachingTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.SectionItem", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.ContentBlockVersion", null)
                        .WithMany()
                        .HasForeignKey("LockedContentBlockVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordSolution.CmsV2.Domain.Entities.SectionItem", null)
                        .WithMany()
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordSolution.CmsV2.Domain.Entities.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.SectionVariant", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.SectionVariantItem", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.SectionItem", null)
                        .WithMany()
                        .HasForeignKey("SectionItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordSolution.CmsV2.Domain.Entities.SectionVariant", null)
                        .WithMany()
                        .HasForeignKey("SectionVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.TagBinding", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.TeachingNoteBinding", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.TeachingNote", null)
                        .WithMany()
                        .HasForeignKey("TeachingNoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WordSolution.CmsV2.Domain.Entities.TeachingTopic", b =>
                {
                    b.HasOne("WordSolution.CmsV2.Domain.Entities.TeachingTopic", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
